<?php

namespace App\Services\AI;

use App\Services\AI\Contracts\LLMProviderInterface;
use App\Services\AI\WebProviders\ChatGPTWebProvider;
use App\Services\AI\WebProviders\ClaudeWebProvider;
use App\Services\AI\WebProviders\GeminiWebProvider;
use Illuminate\Support\Facades\Auth;

class WebAiProvider implements LLMProviderInterface
{
    private array $providerMap = [
        'gpt'    => ChatGPTWebProvider::class,
        'chatgpt' => ChatGPTWebProvider::class,
        'gemini'  => GeminiWebProvider::class,
        'claude'  => ClaudeWebProvider::class,
    ];

    public function streamResponse(array $messages, string $model, array $options = []): \Generator
    {
        // Web-account models (claude.ai, etc.) can't be reached from the server —
        // Cloudflare blocks non-browser requests. Their answers are generated by
        // the Rynude browser extension inside a real provider tab and delivered
        // via ChatApiController::send's `precomputed_response`. Reaching here
        // means the extension path did not run (extension missing / not on the
        // api-keys page / no logged-in provider tab), so guide the user.
        yield "\n[Butuh Rynude Extension untuk akun web. Pastikan extension aktif dan kamu sudah login di tab provider (mis. claude.ai). "
            . "Atau isi API key resmi di Settings.]";
    }

    public function resolve(string $model): ChatGPTWebProvider|GeminiWebProvider|ClaudeWebProvider|null
    {
        foreach ($this->providerMap as $prefix => $class) {
            if (str_starts_with($model, $prefix)) {
                return $class::forCurrentUser($prefix === 'gpt' ? 'chatgpt' : $prefix);
            }
        }

        return null;
    }

    public static function available(): bool
    {
        $user = Auth::user();
        if (!$user) {
            return false;
        }

        return \App\Models\ProviderWebToken::where('user_id', $user->id)
            ->where('status', 'active')
            ->exists();
    }
}
